package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	agentruntime "csgclaw/internal/runtime"
)

const (
	csgclawProviderBeginMarker      = "# BEGIN csgclaw-managed provider (do not edit; regenerated by runtime)"
	csgclawProviderEndMarker        = "# END csgclaw-managed provider"
	csgclawSandboxBeginMarker       = "# BEGIN csgclaw-managed sandbox (do not edit; regenerated by runtime)"
	csgclawSandboxEndMarker         = "# END csgclaw-managed sandbox"
	csgclawMultiAgentBeginMarker    = "# BEGIN csgclaw-managed multi-agent (do not edit; regenerated by runtime)"
	csgclawMultiAgentEndMarker      = "# END csgclaw-managed multi-agent"
	csgclawMemoryFeatureBeginMarker = "# BEGIN csgclaw-managed memory-feature (do not edit; regenerated by runtime)"
	csgclawMemoryFeatureEndMarker   = "# END csgclaw-managed memory-feature"
	csgclawMemoryConfigBeginMarker  = "# BEGIN csgclaw-managed memory-config (do not edit; regenerated by runtime)"
	csgclawMemoryConfigEndMarker    = "# END csgclaw-managed memory-config"
)

var (
	rootFeaturesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*features\s*\]\s*(?:#.*)?$`)
	rootMemoriesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*memories\s*\]\s*(?:#.*)?$`)

	rootDottedMultiAgentRe    = regexp.MustCompile(`^\s*features\s*\.\s*multi_agent\s*=`)
	featuresTableMultiAgentRe = regexp.MustCompile(`^\s*multi_agent\s*=`)

	rootDottedFeaturesMemoriesRe = regexp.MustCompile(`^\s*features\s*\.\s*memories\s*=`)
	featuresTableMemoriesRe      = regexp.MustCompile(`^\s*memories\s*=`)
	rootDottedMemoriesGenerateRe = regexp.MustCompile(`^\s*memories\s*\.\s*generate_memories\s*=`)
	rootDottedMemoriesUseRe      = regexp.MustCompile(`^\s*memories\s*\.\s*use_memories\s*=`)
	memoriesTableGenerateRe      = regexp.MustCompile(`^\s*generate_memories\s*=`)
	memoriesTableUseRe           = regexp.MustCompile(`^\s*use_memories\s*=`)
)

func (r *Runtime) hostCodexConfig() ([]byte, error) {
	path, err := hostCodexConfigPath()
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path)
}

func buildProviderConfigBlock(profile agentruntime.Profile) string {
	profile = profile.Normalized()
	if profile.BaseURL == "" || profile.ModelID == "" {
		return ""
	}

	var b strings.Builder
	b.WriteString(csgclawProviderBeginMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "model = %s\n", strconv.Quote(profile.ModelID))
	fmt.Fprintf(&b, "model_provider = %s\n", strconv.Quote(codexProxyProviderName))
	fmt.Fprintf(&b, "model_catalog_json = %s\n\n", strconv.Quote(modelCatalogFileName))
	fmt.Fprintf(&b, "[model_providers.%s]\n", codexProxyProviderName)
	fmt.Fprintf(&b, "name = %s\n", strconv.Quote("OpenAI using LLM proxy"))
	fmt.Fprintf(&b, "base_url = %s\n", strconv.Quote(profile.BaseURL))
	fmt.Fprintf(&b, "wire_api = %s\n", strconv.Quote("responses"))
	fmt.Fprintf(&b, "supports_websockets = false\n")
	if profile.APIKey != "" {
		fmt.Fprintf(&b, "env_key = %s\n", strconv.Quote("OPENAI_API_KEY"))
	}
	b.WriteString(csgclawProviderEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildSandboxConfigBlock() string {
	var b strings.Builder
	b.WriteString(csgclawSandboxBeginMarker)
	b.WriteString("\n")
	b.WriteString(`sandbox_mode = "workspace-write"` + "\n")
	b.WriteString("sandbox_workspace_write.network_access = true\n")
	b.WriteString(csgclawSandboxEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMultiAgentConfigBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMultiAgentBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("multi_agent = false\n")
	} else {
		b.WriteString("features.multi_agent = false\n")
	}
	b.WriteString(csgclawMultiAgentEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMemoryFeatureConfigBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMemoryFeatureBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("memories = false\n")
	} else {
		b.WriteString("features.memories = false\n")
	}
	b.WriteString(csgclawMemoryFeatureEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMemoryConfigBlock(inMemoriesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMemoryConfigBeginMarker)
	b.WriteString("\n")
	if inMemoriesTable {
		b.WriteString("generate_memories = false\n")
		b.WriteString("use_memories = false\n")
	} else {
		b.WriteString("memories.generate_memories = false\n")
		b.WriteString("memories.use_memories = false\n")
	}
	b.WriteString(csgclawMemoryConfigEndMarker)
	b.WriteString("\n")
	return b.String()
}

func configureCodexHomeConfig(existing string, profile agentruntime.Profile) string {
	content := sanitizeCopiedCodexConfigContent(existing)
	content = strings.TrimLeft(content, "\n")

	content = stripManagedBlock(content, csgclawProviderBeginMarker, csgclawProviderEndMarker)
	content = stripManagedBlock(content, csgclawSandboxBeginMarker, csgclawSandboxEndMarker)
	content = stripManagedBlock(content, csgclawMultiAgentBeginMarker, csgclawMultiAgentEndMarker)
	content = stripManagedBlock(content, csgclawMemoryFeatureBeginMarker, csgclawMemoryFeatureEndMarker)
	content = stripManagedBlock(content, csgclawMemoryConfigBeginMarker, csgclawMemoryConfigEndMarker)

	content = stripLegacySandboxDirectives(content)
	content = stripUserMultiAgentDirectives(content)
	content = stripUserMemoryDirectives(content)

	if block := buildMemoryConfigBlock(hasRootMemoriesTable(content)); block != "" {
		if hasRootMemoriesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootMemoriesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	if block := buildMemoryFeatureConfigBlock(hasRootFeaturesTable(content)); block != "" {
		if hasRootFeaturesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootFeaturesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	if block := buildMultiAgentConfigBlock(hasRootFeaturesTable(content)); block != "" {
		if hasRootFeaturesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootFeaturesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	content = hoistManagedBlock(content, buildSandboxConfigBlock())
	if block := buildProviderConfigBlock(profile); block != "" {
		content = hoistManagedBlock(content, block)
	}

	content = strings.TrimLeft(content, "\n")
	if strings.TrimSpace(content) == "" {
		return ""
	}
	return strings.TrimRight(content, "\n") + "\n"
}

func sanitizeCopiedCodexConfigContent(content string) string {
	if !strings.Contains(content, "[[skills.config]]") {
		return content
	}
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	inSkillsConfig := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			if trimmed == "[[skills.config]]" {
				inSkillsConfig = true
				continue
			}
			inSkillsConfig = false
			out = append(out, line)
			continue
		}
		if inSkillsConfig {
			continue
		}
		out = append(out, line)
	}
	stripped := strings.Join(out, "\n")
	stripped = regexp.MustCompile(`\n{3,}`).ReplaceAllString(stripped, "\n\n")
	if strings.TrimSpace(stripped) == "" {
		return ""
	}
	return strings.TrimRight(stripped, "\n") + "\n"
}

func stripManagedBlock(content, beginMarker, endMarker string) string {
	re := regexp.MustCompile(`(?ms)^` + regexp.QuoteMeta(beginMarker) + `.*?^` + regexp.QuoteMeta(endMarker) + `\n*`)
	return re.ReplaceAllString(content, "")
}

func hoistManagedBlock(content, block string) string {
	block = strings.TrimRight(block, "\n") + "\n"
	content = strings.TrimLeft(content, "\n")
	if content == "" {
		return block
	}
	return block + "\n" + content
}

func hasRootFeaturesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootFeaturesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func hasRootMemoriesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootMemoriesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func injectManagedBlockAfterHeader(content string, headerRe *regexp.Regexp, block string) string {
	blockLines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if !headerRe.MatchString(line) {
			continue
		}
		out := make([]string, 0, len(lines)+len(blockLines))
		out = append(out, lines[:i+1]...)
		out = append(out, blockLines...)
		if i+1 < len(lines) && lines[i+1] != "" {
			out = append(out, "")
		}
		out = append(out, lines[i+1:]...)
		return strings.Join(out, "\n")
	}
	return content
}

func stripLegacySandboxDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	inSandboxWorkspaceWrite := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			inSandboxWorkspaceWrite = trimmed == "[sandbox_workspace_write]"
			if inSandboxWorkspaceWrite {
				continue
			}
			out = append(out, line)
			continue
		}
		if inSandboxWorkspaceWrite {
			continue
		}
		if strings.HasPrefix(trimmed, "sandbox_mode") || strings.HasPrefix(trimmed, "sandbox_workspace_write.") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func stripUserMultiAgentDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedMultiAgentRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMultiAgentRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func stripUserMemoryDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if rootMemoriesTableHeaderRe.MatchString(line) {
			currentTable = "[memories]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedFeaturesMemoriesRe.MatchString(trimmed) ||
				rootDottedMemoriesGenerateRe.MatchString(trimmed) ||
				rootDottedMemoriesUseRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMemoriesRe.MatchString(trimmed) {
				continue
			}
		case "[memories]":
			if memoriesTableGenerateRe.MatchString(trimmed) || memoriesTableUseRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func hostCodexConfigPath() (string, error) {
	if home := strings.TrimSpace(os.Getenv("CODEX_HOME")); home != "" {
		return filepath.Join(home, configFileName), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".codex", configFileName), nil
}
