package codex

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	agentruntime "csgclaw/internal/runtime"

	toml "github.com/pelletier/go-toml/v2"
)

const (
	csgclawProviderBeginMarker      = "# BEGIN csgclaw-managed provider (do not edit; regenerated by runtime)"
	csgclawProviderEndMarker        = "# END csgclaw-managed provider"
	csgclawSandboxBeginMarker       = "# BEGIN csgclaw-managed sandbox (do not edit; regenerated by runtime)"
	csgclawSandboxEndMarker         = "# END csgclaw-managed sandbox"
	csgclawMultiAgentBeginMarker    = "# BEGIN csgclaw-managed multi-agent (do not edit; regenerated by runtime)"
	csgclawMultiAgentEndMarker      = "# END csgclaw-managed multi-agent"
	csgclawUserInputBeginMarker     = "# BEGIN csgclaw-managed user-input (do not edit; regenerated by runtime)"
	csgclawUserInputEndMarker       = "# END csgclaw-managed user-input"
	csgclawMemoryFeatureBeginMarker = "# BEGIN csgclaw-managed memory-feature (do not edit; regenerated by runtime)"
	csgclawMemoryFeatureEndMarker   = "# END csgclaw-managed memory-feature"
	csgclawMemoryConfigBeginMarker  = "# BEGIN csgclaw-managed memory-config (do not edit; regenerated by runtime)"
	csgclawMemoryConfigEndMarker    = "# END csgclaw-managed memory-config"
	csgclawMCPBeginMarker           = "# BEGIN csgclaw-managed mcp (do not edit; regenerated by runtime)"
	csgclawMCPEndMarker             = "# END csgclaw-managed mcp"
)

var (
	rootFeaturesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*features\s*\]\s*(?:#.*)?$`)
	rootMemoriesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*memories\s*\]\s*(?:#.*)?$`)
	mcpServersTableHeaderRe   = regexp.MustCompile(`^\s*\[\s*mcp_servers\s*(?:\.\s*(?:"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|[A-Za-z0-9_-]+)\s*)*\]\s*(?:#.*)?$`)

	rootDottedMultiAgentRe    = regexp.MustCompile(`^\s*features\s*\.\s*multi_agent\s*=`)
	featuresTableMultiAgentRe = regexp.MustCompile(`^\s*multi_agent\s*=`)
	rootDottedUserInputRe     = regexp.MustCompile(`^\s*features\s*\.\s*default_mode_request_user_input\s*=`)
	featuresTableUserInputRe  = regexp.MustCompile(`^\s*default_mode_request_user_input\s*=`)

	rootDottedFeaturesMemoriesRe = regexp.MustCompile(`^\s*features\s*\.\s*memories\s*=`)
	featuresTableMemoriesRe      = regexp.MustCompile(`^\s*memories\s*=`)
	rootDottedMemoriesGenerateRe = regexp.MustCompile(`^\s*memories\s*\.\s*generate_memories\s*=`)
	rootDottedMemoriesUseRe      = regexp.MustCompile(`^\s*memories\s*\.\s*use_memories\s*=`)
	memoriesTableGenerateRe      = regexp.MustCompile(`^\s*generate_memories\s*=`)
	memoriesTableUseRe           = regexp.MustCompile(`^\s*use_memories\s*=`)
)

func (r *Runtime) hostCodexConfig() ([]byte, error) {
	path, err := hostCodexConfigPath()
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path)
}

func buildProviderConfigBlock(profile agentruntime.Profile) string {
	profile = profile.Normalized()
	if profile.BaseURL == "" || profile.ModelID == "" {
		return ""
	}

	var b strings.Builder
	b.WriteString(csgclawProviderBeginMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "model = %s\n", strconv.Quote(profile.ModelID))
	fmt.Fprintf(&b, "model_provider = %s\n", strconv.Quote(codexProxyProviderName))
	fmt.Fprintf(&b, "model_catalog_json = %s\n\n", strconv.Quote(modelCatalogFileName))
	fmt.Fprintf(&b, "[model_providers.%s]\n", codexProxyProviderName)
	fmt.Fprintf(&b, "name = %s\n", strconv.Quote("OpenAI using LLM proxy"))
	fmt.Fprintf(&b, "base_url = %s\n", strconv.Quote(profile.BaseURL))
	fmt.Fprintf(&b, "wire_api = %s\n", strconv.Quote("responses"))
	fmt.Fprintf(&b, "supports_websockets = false\n")
	if profile.APIKey != "" {
		fmt.Fprintf(&b, "env_key = %s\n", strconv.Quote("OPENAI_API_KEY"))
	}
	b.WriteString(csgclawProviderEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildSandboxConfigBlock() string {
	var b strings.Builder
	b.WriteString(csgclawSandboxBeginMarker)
	b.WriteString("\n")
	b.WriteString(`sandbox_mode = "workspace-write"` + "\n")
	b.WriteString("sandbox_workspace_write.network_access = true\n")
	b.WriteString(csgclawSandboxEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMultiAgentConfigBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMultiAgentBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("multi_agent = false\n")
	} else {
		b.WriteString("features.multi_agent = false\n")
	}
	b.WriteString(csgclawMultiAgentEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildUserInputConfigBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawUserInputBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("default_mode_request_user_input = true\n")
	} else {
		b.WriteString("features.default_mode_request_user_input = true\n")
	}
	b.WriteString(csgclawUserInputEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMemoryFeatureConfigBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMemoryFeatureBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("memories = false\n")
	} else {
		b.WriteString("features.memories = false\n")
	}
	b.WriteString(csgclawMemoryFeatureEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMemoryConfigBlock(inMemoriesTable bool) string {
	var b strings.Builder
	b.WriteString(csgclawMemoryConfigBeginMarker)
	b.WriteString("\n")
	if inMemoriesTable {
		b.WriteString("generate_memories = false\n")
		b.WriteString("use_memories = false\n")
	} else {
		b.WriteString("memories.generate_memories = false\n")
		b.WriteString("memories.use_memories = false\n")
	}
	b.WriteString(csgclawMemoryConfigEndMarker)
	b.WriteString("\n")
	return b.String()
}

func buildMCPServersBlock(mcpServers map[string]any, workspaceDir string) (string, error) {
	servers, err := agentruntime.NormalizeMCPServers(mcpServers)
	if err != nil {
		return "", err
	}
	if servers == nil {
		return "", nil
	}

	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(csgclawMCPBeginMarker)
	b.WriteString("\n")
	for idx, name := range names {
		entry, ok := servers[name].(map[string]any)
		if !ok {
			return "", fmt.Errorf("%s.%s must be an object", agentruntime.MCPServersKey, name)
		}
		if idx > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "[mcp_servers.%s]\n", tomlQuotedKey(name))
		if url := mcpTrimmedString(entry["url"]); url != "" {
			fmt.Fprintf(&b, "url = %s\n", strconv.Quote(url))
			writeCodexMCPStringFields(&b, entry)
			if headers := mcpStringMap(entry["headers"]); len(headers) > 0 {
				fmt.Fprintf(&b, "http_headers = %s\n", tomlInlineStringMap(headers))
			}
			writeCodexMCPCommonFields(&b, entry)
			continue
		}
		command := mcpTrimmedString(entry["command"])
		if command == "" {
			return "", fmt.Errorf("%s.%s must declare command or url", agentruntime.MCPServersKey, name)
		}
		fmt.Fprintf(&b, "command = %s\n", strconv.Quote(command))
		if args := mcpStringSlice(entry["args"]); len(args) > 0 {
			args = resolveCodexMCPWorkspaceArgs(args, workspaceDir)
			fmt.Fprintf(&b, "args = %s\n", tomlStringArray(args))
		}
		if env := mcpStringMap(entry["env"]); len(env) > 0 {
			fmt.Fprintf(&b, "env = %s\n", tomlInlineStringMap(env))
		}
		writeCodexMCPCommonFields(&b, entry)
	}
	b.WriteString(csgclawMCPEndMarker)
	b.WriteString("\n")
	return b.String(), nil
}

func resolveCodexMCPWorkspaceArgs(args []string, workspaceDir string) []string {
	workspaceDir = strings.TrimSpace(workspaceDir)
	if workspaceDir == "" {
		return args
	}
	out := make([]string, len(args))
	for idx, arg := range args {
		out[idx] = resolveCodexMCPWorkspaceArg(arg, workspaceDir)
	}
	return out
}

func resolveCodexMCPWorkspaceArg(arg, workspaceDir string) string {
	for _, placeholder := range []string{"${workspace}", "${workspaceDir}", "{workspace}", "{workspaceDir}"} {
		if arg == placeholder {
			return workspaceDir
		}
		if strings.HasPrefix(arg, placeholder+"/") {
			return filepath.Join(workspaceDir, strings.TrimPrefix(arg, placeholder+"/"))
		}
	}
	return arg
}

func parseCodexMCPServers(content string) (map[string]any, error) {
	if strings.TrimSpace(content) == "" {
		return nil, nil
	}
	var cfg map[string]any
	if err := toml.Unmarshal([]byte(content), &cfg); err != nil {
		return nil, fmt.Errorf("decode codex mcp config: %w", err)
	}
	rawServers, ok := cfg["mcp_servers"]
	if !ok || rawServers == nil {
		return nil, nil
	}
	servers, ok := rawServers.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("codex mcp_servers must be an object")
	}
	servers = codexMCPServersToGeneric(servers)
	normalized, err := agentruntime.NormalizeMCPServers(servers)
	if err != nil {
		return nil, err
	}
	return normalized, nil
}

func configureCodexHomeConfig(existing string, profile agentruntime.Profile, mcpServers map[string]any) string {
	return configureCodexHomeConfigWithWorkspace(existing, profile, mcpServers, "")
}

func configureCodexHomeConfigWithWorkspace(existing string, profile agentruntime.Profile, mcpServers map[string]any, workspaceDir string) string {
	content := sanitizeCopiedCodexConfigContent(existing)
	content = strings.TrimLeft(content, "\n")

	content = stripManagedBlock(content, csgclawProviderBeginMarker, csgclawProviderEndMarker)
	content = stripManagedBlock(content, csgclawSandboxBeginMarker, csgclawSandboxEndMarker)
	content = stripManagedBlock(content, csgclawMultiAgentBeginMarker, csgclawMultiAgentEndMarker)
	content = stripManagedBlock(content, csgclawUserInputBeginMarker, csgclawUserInputEndMarker)
	content = stripManagedBlock(content, csgclawMemoryFeatureBeginMarker, csgclawMemoryFeatureEndMarker)
	content = stripManagedBlock(content, csgclawMemoryConfigBeginMarker, csgclawMemoryConfigEndMarker)
	content = stripManagedBlock(content, csgclawMCPBeginMarker, csgclawMCPEndMarker)
	if mcpServers != nil {
		content = stripTableBlocks(content, mcpServersTableHeaderRe)
	}

	content = stripLegacySandboxDirectives(content)
	content = stripUserMultiAgentDirectives(content)
	content = stripUserInputDirectives(content)
	content = stripUserMemoryDirectives(content)

	if block := buildMemoryConfigBlock(hasRootMemoriesTable(content)); block != "" {
		if hasRootMemoriesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootMemoriesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	if block := buildMemoryFeatureConfigBlock(hasRootFeaturesTable(content)); block != "" {
		if hasRootFeaturesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootFeaturesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	if block := buildMultiAgentConfigBlock(hasRootFeaturesTable(content)); block != "" {
		if hasRootFeaturesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootFeaturesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	if block := buildUserInputConfigBlock(hasRootFeaturesTable(content)); block != "" {
		if hasRootFeaturesTable(content) {
			content = injectManagedBlockAfterHeader(content, rootFeaturesTableHeaderRe, block)
		} else {
			content = hoistManagedBlock(content, block)
		}
	}
	content = hoistManagedBlock(content, buildSandboxConfigBlock())
	if block := buildProviderConfigBlock(profile); block != "" {
		content = hoistManagedBlock(content, block)
	}
	if block, err := buildMCPServersBlock(mcpServers, workspaceDir); err == nil && block != "" {
		content = appendManagedBlock(content, block)
	}

	content = strings.TrimLeft(content, "\n")
	if strings.TrimSpace(content) == "" {
		return ""
	}
	return strings.TrimRight(content, "\n") + "\n"
}

func mcpTrimmedString(value any) string {
	text, _ := value.(string)
	return strings.TrimSpace(text)
}

func mcpStringSlice(value any) []string {
	switch raw := value.(type) {
	case []any:
		out := make([]string, 0, len(raw))
		for _, item := range raw {
			text, ok := item.(string)
			if !ok {
				return nil
			}
			out = append(out, text)
		}
		return out
	case []string:
		return append([]string(nil), raw...)
	default:
		return nil
	}
}

func mcpStringMap(value any) map[string]string {
	switch raw := value.(type) {
	case map[string]any:
		out := make(map[string]string, len(raw))
		for key, item := range raw {
			text, ok := item.(string)
			if !ok {
				return nil
			}
			out[key] = text
		}
		return out
	case map[string]string:
		out := make(map[string]string, len(raw))
		for key, item := range raw {
			out[key] = item
		}
		return out
	default:
		return nil
	}
}

func writeCodexMCPStringFields(b *strings.Builder, entry map[string]any) {
	for _, key := range []string{"bearer_token_env_var", "oauth_client_id", "oauth_resource"} {
		if value := mcpTrimmedString(entry[key]); value != "" {
			fmt.Fprintf(b, "%s = %s\n", key, strconv.Quote(value))
		}
	}
}

func writeCodexMCPCommonFields(b *strings.Builder, entry map[string]any) {
	for _, key := range []string{"cwd", "default_tools_approval_mode", "experimental_environment"} {
		if value := mcpTrimmedString(entry[key]); value != "" {
			fmt.Fprintf(b, "%s = %s\n", key, strconv.Quote(value))
		}
	}
	for _, key := range []string{"startup_timeout_sec", "tool_timeout_sec"} {
		if value, ok := mcpInteger(entry[key]); ok {
			fmt.Fprintf(b, "%s = %d\n", key, value)
		}
	}
	for _, key := range []string{"enabled", "required"} {
		if value, ok := entry[key].(bool); ok {
			fmt.Fprintf(b, "%s = %t\n", key, value)
		}
	}
	for _, key := range []string{"enabled_tools", "disabled_tools", "env_vars"} {
		if values := mcpStringSlice(entry[key]); len(values) > 0 {
			fmt.Fprintf(b, "%s = %s\n", key, tomlStringArray(values))
		}
	}
	if headers := mcpStringMap(entry["env_http_headers"]); len(headers) > 0 {
		fmt.Fprintf(b, "env_http_headers = %s\n", tomlInlineStringMap(headers))
	}
}

func mcpInteger(value any) (int64, bool) {
	switch typed := value.(type) {
	case int:
		if typed <= 0 {
			return 0, false
		}
		return int64(typed), true
	case int8:
		if typed <= 0 {
			return 0, false
		}
		return int64(typed), true
	case int16:
		if typed <= 0 {
			return 0, false
		}
		return int64(typed), true
	case int32:
		if typed <= 0 {
			return 0, false
		}
		return int64(typed), true
	case int64:
		if typed <= 0 {
			return 0, false
		}
		return typed, true
	case uint:
		if typed == 0 || uint64(typed) > math.MaxInt64 {
			return 0, false
		}
		return int64(typed), true
	case uint8:
		if typed == 0 {
			return 0, false
		}
		return int64(typed), true
	case uint16:
		if typed == 0 {
			return 0, false
		}
		return int64(typed), true
	case uint32:
		if typed == 0 {
			return 0, false
		}
		return int64(typed), true
	case uint64:
		if typed == 0 || typed > math.MaxInt64 {
			return 0, false
		}
		return int64(typed), true
	case float64:
		if !validMCPIntegerFloat(typed) {
			return 0, false
		}
		return int64(typed), true
	default:
		return 0, false
	}
}

func validMCPIntegerFloat(value float64) bool {
	// float64(math.MaxInt64) rounds up to 1<<63; values at that boundary cannot
	// be safely converted back to int64 for Codex's integer TOML fields.
	return !math.IsNaN(value) &&
		!math.IsInf(value, 0) &&
		math.Trunc(value) == value &&
		value > 0 &&
		value < float64(math.MaxInt64)
}

func codexMCPServersToGeneric(servers map[string]any) map[string]any {
	out := make(map[string]any, len(servers))
	for name, rawEntry := range servers {
		entry, ok := rawEntry.(map[string]any)
		if !ok {
			out[name] = rawEntry
			continue
		}
		normalized := make(map[string]any, len(entry))
		for key, value := range entry {
			if key == "http_headers" {
				if _, exists := entry["headers"]; !exists {
					normalized["headers"] = value
				}
				continue
			}
			normalized[key] = value
		}
		if _, exists := normalized["transport"]; !exists {
			if mcpTrimmedString(normalized["url"]) != "" {
				normalized["transport"] = "streamable-http"
			}
		}
		out[name] = normalized
	}
	return out
}

func tomlQuotedKey(key string) string {
	return strconv.Quote(strings.TrimSpace(key))
}

func tomlStringArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func tomlInlineStringMap(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	items := make([]string, 0, len(keys))
	for _, key := range keys {
		items = append(items, strconv.Quote(key)+" = "+strconv.Quote(values[key]))
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func sanitizeCopiedCodexConfigContent(content string) string {
	if !strings.Contains(content, "[[skills.config]]") {
		return content
	}
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	inSkillsConfig := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			if trimmed == "[[skills.config]]" {
				inSkillsConfig = true
				continue
			}
			inSkillsConfig = false
			out = append(out, line)
			continue
		}
		if inSkillsConfig {
			continue
		}
		out = append(out, line)
	}
	stripped := strings.Join(out, "\n")
	stripped = regexp.MustCompile(`\n{3,}`).ReplaceAllString(stripped, "\n\n")
	if strings.TrimSpace(stripped) == "" {
		return ""
	}
	return strings.TrimRight(stripped, "\n") + "\n"
}

func stripManagedBlock(content, beginMarker, endMarker string) string {
	re := regexp.MustCompile(`(?ms)^` + regexp.QuoteMeta(beginMarker) + `.*?^` + regexp.QuoteMeta(endMarker) + `\n*`)
	return re.ReplaceAllString(content, "")
}

func stripTableBlocks(content string, tableHeaderRe *regexp.Regexp) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	skipping := false
	for _, line := range lines {
		if isTOMLTableHeader(line) {
			skipping = tableHeaderRe.MatchString(line)
		}
		if skipping {
			continue
		}
		out = append(out, line)
	}
	stripped := strings.Join(out, "\n")
	stripped = regexp.MustCompile(`\n{3,}`).ReplaceAllString(stripped, "\n\n")
	return strings.TrimRight(stripped, "\n")
}

func isTOMLTableHeader(line string) bool {
	trimmed := strings.TrimSpace(line)
	return strings.HasPrefix(trimmed, "[")
}

func hoistManagedBlock(content, block string) string {
	block = strings.TrimRight(block, "\n") + "\n"
	content = strings.TrimLeft(content, "\n")
	if content == "" {
		return block
	}
	return block + "\n" + content
}

func appendManagedBlock(content, block string) string {
	block = strings.TrimRight(block, "\n") + "\n"
	content = strings.TrimRight(content, "\n")
	if content == "" {
		return block
	}
	return content + "\n\n" + block
}

func hasRootFeaturesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootFeaturesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func hasRootMemoriesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootMemoriesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func injectManagedBlockAfterHeader(content string, headerRe *regexp.Regexp, block string) string {
	blockLines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if !headerRe.MatchString(line) {
			continue
		}
		out := make([]string, 0, len(lines)+len(blockLines))
		out = append(out, lines[:i+1]...)
		out = append(out, blockLines...)
		if i+1 < len(lines) && lines[i+1] != "" {
			out = append(out, "")
		}
		out = append(out, lines[i+1:]...)
		return strings.Join(out, "\n")
	}
	return content
}

func stripLegacySandboxDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	inSandboxWorkspaceWrite := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			inSandboxWorkspaceWrite = trimmed == "[sandbox_workspace_write]"
			if inSandboxWorkspaceWrite {
				continue
			}
			out = append(out, line)
			continue
		}
		if inSandboxWorkspaceWrite {
			continue
		}
		if strings.HasPrefix(trimmed, "sandbox_mode") || strings.HasPrefix(trimmed, "sandbox_workspace_write.") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func stripUserMultiAgentDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedMultiAgentRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMultiAgentRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func stripUserInputDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedUserInputRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableUserInputRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func stripUserMemoryDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if rootMemoriesTableHeaderRe.MatchString(line) {
			currentTable = "[memories]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedFeaturesMemoriesRe.MatchString(trimmed) ||
				rootDottedMemoriesGenerateRe.MatchString(trimmed) ||
				rootDottedMemoriesUseRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMemoriesRe.MatchString(trimmed) {
				continue
			}
		case "[memories]":
			if memoriesTableGenerateRe.MatchString(trimmed) || memoriesTableUseRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func hostCodexConfigPath() (string, error) {
	if home := strings.TrimSpace(os.Getenv("CODEX_HOME")); home != "" {
		return filepath.Join(home, configFileName), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".codex", configFileName), nil
}
