package onboard

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"csgclaw/cli/command"
	"csgclaw/internal/bot"
	"csgclaw/internal/config"
	internalonboard "csgclaw/internal/onboard"
)

func TestRunInteractiveFreshSkipsModelProviderPrompt(t *testing.T) {
	restore := stubBootstrap(t, func(_ context.Context, _, _ string, cfg config.Config) error {
		if !cfg.Models.IsZero() || !cfg.LLM.IsZero() {
			t.Fatalf("cfg should not include static LLM models: models=%+v llm=%+v", cfg.Models, cfg.LLM)
		}
		if got, want := cfg.Sandbox.Provider, config.DefaultSandboxProvider; got != want {
			t.Fatalf("cfg.Sandbox.Provider = %q, want %q", got, want)
		}
		if got, want := cfg.Sandbox.HomeDirName, config.DefaultSandboxHomeDirName; got != want {
			t.Fatalf("cfg.Sandbox.HomeDirName = %q, want %q", got, want)
		}
		return nil
	})
	defer restore()

	configPath := filepath.Join(t.TempDir(), "config.toml")
	run := interactiveTestContext("ignored\n")
	if err := NewCmd().Run(context.Background(), run, nil, command.GlobalOptions{Config: configPath, Output: "table"}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	output := run.Stdout.(*fakeTerminalBuffer).String()
	for _, forbidden := range []string{
		"CSGClaw model provider setup",
		"CSGHub-lite base URL",
		"Checking CSGHub-lite models",
		"Using CSGHub-lite provider",
	} {
		if strings.Contains(output, forbidden) {
			t.Fatalf("prompt output contains %q:\n%s", forbidden, output)
		}
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	content := string(data)
	if strings.Contains(content, "[models]") || strings.Contains(content, "[models.providers.") {
		t.Fatalf("saved config should not contain static model config:\n%s", content)
	}
	for _, want := range []string{
		`[server]`,
		`[bootstrap]`,
		`manager_image_override = ""`,
		`[sandbox]`,
		fmt.Sprintf(`provider = %q`, config.DefaultSandboxProvider),
		fmt.Sprintf(`home_dir_name = %q`, config.DefaultSandboxHomeDirName),
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("saved config missing %q:\n%s", want, content)
		}
	}
}

func TestRunFreshNonInteractiveAllowsMissingLLMConfig(t *testing.T) {
	callCount := 0
	restore := stubBootstrap(t, func(_ context.Context, _, _ string, cfg config.Config) error {
		callCount++
		if !cfg.Models.IsZero() || !cfg.LLM.IsZero() {
			t.Fatalf("cfg should not include static LLM models: models=%+v llm=%+v", cfg.Models, cfg.LLM)
		}
		return nil
	})
	defer restore()

	configPath := filepath.Join(t.TempDir(), "config.toml")
	run := testContext()
	if err := NewCmd().Run(context.Background(), run, nil, command.GlobalOptions{Config: configPath}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if callCount != 1 {
		t.Fatalf("bootstrap call count = %d, want 1", callCount)
	}
}

func TestRunPreservesExistingStaticLLMConfigWithoutPrompting(t *testing.T) {
	restore := stubBootstrap(t, func(_ context.Context, _, _ string, cfg config.Config) error {
		if got, want := cfg.Models.Default, "default.gpt-test"; got != want {
			t.Fatalf("cfg.Models.Default = %q, want %q", got, want)
		}
		return nil
	})
	defer restore()
	configPath := filepath.Join(t.TempDir(), "config.toml")
	if err := writeConfig(configPath, `# Generated by csgclaw onboard.

[server]
listen_addr = "0.0.0.0:18080"
advertise_base_url = ""
access_token = "your_access_token"

[bootstrap]
manager_image_override = "img"

[models]
default = "default.gpt-test"

[models.providers.default]
base_url = "http://llm.test/v1"
api_key = "secret"
models = ["gpt-test"]
`); err != nil {
		t.Fatalf("writeConfig() error = %v", err)
	}

	run := interactiveTestContext("\n")
	if err := NewCmd().Run(context.Background(), run, nil, command.GlobalOptions{Config: configPath, Output: "table"}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	output := run.Stdout.(*fakeTerminalBuffer).String()
	if strings.Contains(output, "Current model configuration:") || strings.Contains(output, "Provider:") || strings.Contains(output, "secret") {
		t.Fatalf("onboard should not prompt or echo model provider config:\n%s", output)
	}
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !strings.Contains(string(data), `[models.providers.default]`) {
		t.Fatalf("existing static model config should be preserved:\n%s", string(data))
	}
}

func TestRunRepeatedDoesNotRewriteExistingCompleteConfig(t *testing.T) {
	callCount := 0
	restore := stubBootstrap(t, func(_ context.Context, _, _ string, cfg config.Config) error {
		callCount++
		if got, want := cfg.Server.ListenAddr, "127.0.0.1:19090"; got != want {
			t.Fatalf("cfg.Server.ListenAddr = %q, want %q", got, want)
		}
		return nil
	})
	defer restore()

	configPath := filepath.Join(t.TempDir(), "config.toml")
	original := `# custom config header

[server]
listen_addr = "127.0.0.1:19090"
advertise_base_url = "http://example.test"
access_token = "custom-token"
no_auth = false

[bootstrap]
manager_image_override = ""

[sandbox]
provider = "boxlite-cli"
home_dir_name = "boxlite"

[models]
default = "default.gpt-test"

[models.providers.default]
base_url = "http://llm.test/v1"
api_key = "secret"
models = ["gpt-test"]
`
	if err := writeConfig(configPath, original); err != nil {
		t.Fatalf("writeConfig() error = %v", err)
	}

	run := testContext()
	if err := NewCmd().Run(context.Background(), run, nil, command.GlobalOptions{Config: configPath}); err != nil {
		t.Fatalf("first Run() error = %v", err)
	}
	if err := NewCmd().Run(context.Background(), run, nil, command.GlobalOptions{Config: configPath}); err != nil {
		t.Fatalf("second Run() error = %v", err)
	}

	if callCount != 2 {
		t.Fatalf("bootstrap call count = %d, want 2 across repeated onboard runs", callCount)
	}
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if string(data) != original {
		t.Fatalf("onboard rewrote complete config.\nGot:\n%s\nWant:\n%s", string(data), original)
	}
}

func TestConfigureOnboardLoggerRejectsUnsupportedLevel(t *testing.T) {
	_, err := configureOnboardLogger(&bytes.Buffer{}, "trace")
	if err == nil {
		t.Fatal("configureOnboardLogger() error = nil, want unsupported-level error")
	}
	if !strings.Contains(err.Error(), `unsupported log level "trace"`) {
		t.Fatalf("configureOnboardLogger() error = %q, want unsupported-level error", err)
	}
}

func TestConfigureOnboardLoggerEnablesDebug(t *testing.T) {
	prev := slog.Default()
	t.Cleanup(func() {
		slog.SetDefault(prev)
	})

	restore, err := configureOnboardLogger(&bytes.Buffer{}, "debug")
	if err != nil {
		t.Fatalf("configureOnboardLogger() error = %v", err)
	}
	defer restore()

	if !slog.Default().Enabled(context.Background(), slog.LevelDebug) {
		t.Fatal("default logger debug level is disabled, want enabled")
	}
}

func TestConfigureOnboardLoggerUsesCompactTerminalFormat(t *testing.T) {
	prev := slog.Default()
	origTerminal := isTerminalFD
	t.Cleanup(func() {
		slog.SetDefault(prev)
		isTerminalFD = origTerminal
	})
	isTerminalFD = func(int) bool { return true }

	buf := &fakeTerminalBuffer{}
	restore, err := configureOnboardLogger(buf, "debug")
	if err != nil {
		t.Fatalf("configureOnboardLogger() error = %v", err)
	}
	defer restore()

	slog.Debug("running boxlite cli command: /tmp/boxlite inspect --format json manager")
	got := buf.String()
	if !strings.Contains(got, "DEBUG running boxlite cli command: /tmp/boxlite inspect --format json manager") {
		t.Fatalf("terminal log = %q, want compact debug format", got)
	}
	if strings.Contains(got, "level=DEBUG") || strings.Contains(got, "msg=") || strings.Contains(got, "time=") {
		t.Fatalf("terminal log = %q, want no default text-handler fields", got)
	}
}

func TestRunDebianRegistriesFlagPersistsToConfig(t *testing.T) {
	restore := stubBootstrap(t, func(_ context.Context, _, _ string, cfg config.Config) error {
		if got, want := strings.Join(cfg.Sandbox.DebianRegistries, ","), "registry.a,docker.io"; got != want {
			t.Fatalf("bootstrap cfg.Sandbox.DebianRegistries = %q, want %q", got, want)
		}
		return nil
	})
	defer restore()

	configPath := filepath.Join(t.TempDir(), "config.toml")
	run := testContext()
	err := NewCmd().Run(context.Background(), run, []string{
		"--debian-registries", "registry.a,docker.io",
	}, command.GlobalOptions{Config: configPath})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !strings.Contains(string(data), `debian_registries = ["registry.a", "docker.io"]`) {
		t.Fatalf("saved config should persist onboard --debian-registries:\n%s", string(data))
	}
	if strings.Contains(string(data), "[models]") {
		t.Fatalf("saved config should not contain static model config:\n%s", string(data))
	}
}

func testContext() *command.Context {
	return &command.Context{
		Program: "csgclaw",
		Stdout:  &bytes.Buffer{},
		Stderr:  &bytes.Buffer{},
	}
}

func interactiveTestContext(input string) *command.Context {
	return &command.Context{
		Program: "csgclaw",
		Stdin:   fakeTerminalInput{Reader: strings.NewReader(input)},
		Stdout:  &fakeTerminalBuffer{},
		Stderr:  &bytes.Buffer{},
	}
}

type fakeTerminalInput struct {
	*strings.Reader
}

func (fakeTerminalInput) Fd() uintptr {
	return 1
}

type fakeTerminalBuffer struct {
	bytes.Buffer
}

func (*fakeTerminalBuffer) Fd() uintptr {
	return 1
}

func stubBootstrap(t *testing.T, verify func(context.Context, string, string, config.Config) error) func() {
	t.Helper()
	origCreateManager := internalonboard.CreateManagerBot
	origEnsureIMBootstrapState := internalonboard.EnsureIMBootstrapState
	internalonboard.CreateManagerBot = func(ctx context.Context, agentsPath, imStatePath string, cfg config.Config) (bot.Bot, error) {
		if err := verify(ctx, agentsPath, imStatePath, cfg); err != nil {
			return bot.Bot{}, err
		}
		return bot.Bot{}, nil
	}
	internalonboard.EnsureIMBootstrapState = func(string) error { return nil }
	return func() {
		internalonboard.CreateManagerBot = origCreateManager
		internalonboard.EnsureIMBootstrapState = origEnsureIMBootstrapState
	}
}

func writeConfig(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o600)
}
