package onboard

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"csgclaw/internal/agent"
	"csgclaw/internal/bot"
	"csgclaw/internal/config"
)

func TestEnsureStateCreatesConfigAndBootstrapsManagerState(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	configPath := filepath.Join(t.TempDir(), "config.toml")
	wantAgentsPath, err := config.DefaultAgentsPath()
	if err != nil {
		t.Fatalf("DefaultAgentsPath() error = %v", err)
	}
	wantIMStatePath, err := config.DefaultIMStatePath()
	if err != nil {
		t.Fatalf("DefaultIMStatePath() error = %v", err)
	}

	var gotIMStatePath string
	var gotAgentsPath string
	var gotManagerIMStatePath string
	var gotCfg config.Config
	restore := stubEnsureStateDeps(t)
	defer restore()
	EnsureIMBootstrapState = func(path string) error {
		gotIMStatePath = path
		return nil
	}
	CreateManagerBot = func(_ context.Context, agentsPath, imStatePath string, cfg config.Config) (bot.Bot, error) {
		gotAgentsPath = agentsPath
		gotManagerIMStatePath = imStatePath
		gotCfg = cfg
		return bot.Bot{ID: agent.ManagerUserID}, nil
	}

	result, err := EnsureState(context.Background(), EnsureStateOptions{ConfigPath: configPath})
	if err != nil {
		t.Fatalf("EnsureState() error = %v", err)
	}

	if gotIMStatePath != wantIMStatePath {
		t.Fatalf("EnsureIMBootstrapState path = %q, want %q", gotIMStatePath, wantIMStatePath)
	}
	if gotAgentsPath != wantAgentsPath {
		t.Fatalf("CreateManagerBot agentsPath = %q, want %q", gotAgentsPath, wantAgentsPath)
	}
	if gotManagerIMStatePath != wantIMStatePath {
		t.Fatalf("CreateManagerBot imStatePath = %q, want %q", gotManagerIMStatePath, wantIMStatePath)
	}
	if result.ConfigPath != configPath {
		t.Fatalf("result.ConfigPath = %q, want %q", result.ConfigPath, configPath)
	}
	if got, want := gotCfg.Server.ListenAddr, config.DefaultListenAddr(); got != want {
		t.Fatalf("cfg.Server.ListenAddr = %q, want %q", got, want)
	}
	if got, want := gotCfg.Server.AccessToken, config.DefaultAccessToken; got != want {
		t.Fatalf("cfg.Server.AccessToken = %q, want %q", got, want)
	}
	if got, want := gotCfg.Sandbox.Provider, config.DefaultSandboxProvider; got != want {
		t.Fatalf("cfg.Sandbox.Provider = %q, want %q", got, want)
	}
	if got, want := gotCfg.Sandbox.HomeDirName, config.DefaultSandboxHomeDirName; got != want {
		t.Fatalf("cfg.Sandbox.HomeDirName = %q, want %q", got, want)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	for _, want := range []string{
		`[server]`,
		`[bootstrap]`,
		`[sandbox]`,
		`provider = "` + config.DefaultSandboxProvider + `"`,
		`home_dir_name = "` + config.DefaultSandboxHomeDirName + `"`,
		`debian_registries_override = []`,
	} {
		if !strings.Contains(string(data), want) {
			t.Fatalf("saved config missing %q:\n%s", want, string(data))
		}
	}
}

func TestEnsureStatePreservesExistingStaticLLMConfig(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	configPath := filepath.Join(t.TempDir(), "config.toml")
	if err := os.WriteFile(configPath, []byte(`# Generated by csgclaw onboard.

[server]
listen_addr = "0.0.0.0:18080"
advertise_base_url = ""
access_token = "your_access_token"

[bootstrap]
manager_image_override = "img"

[sandbox]
provider = "boxlite-cli"
home_dir_name = "boxlite"
debian_registries_override = []

[models]
default = "default.gpt-test"

[models.providers.default]
base_url = "http://llm.test/v1"
api_key = "secret"
models = ["gpt-test"]
`), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	var gotCfg config.Config
	restore := stubEnsureStateDeps(t)
	defer restore()
	EnsureIMBootstrapState = func(string) error { return nil }
	CreateManagerBot = func(_ context.Context, _, _ string, cfg config.Config) (bot.Bot, error) {
		gotCfg = cfg
		return bot.Bot{}, nil
	}

	if _, err := EnsureState(context.Background(), EnsureStateOptions{ConfigPath: configPath}); err != nil {
		t.Fatalf("EnsureState() error = %v", err)
	}
	if got, want := gotCfg.Models.Default, "default.gpt-test"; got != want {
		t.Fatalf("cfg.Models.Default = %q, want %q", got, want)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if !strings.Contains(string(data), `[models.providers.default]`) {
		t.Fatalf("saved config should preserve static llm config:\n%s", string(data))
	}
	if !strings.Contains(string(data), `api_key = "secret"`) {
		t.Fatalf("saved config should preserve model API key entry:\n%s", string(data))
	}
}

func TestEnsureStateDoesNotRewriteExistingCompleteConfig(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	configPath := filepath.Join(t.TempDir(), "config.toml")
	original := `# custom config header

[server]
listen_addr = "127.0.0.1:19090"
advertise_base_url = "http://example.test"
access_token = "custom-token"
no_auth = false

[bootstrap]
manager_image_override = ""

[sandbox]
provider = "boxlite-cli"
home_dir_name = "boxlite"
debian_registries_override = []

[models]
default = "default.gpt-test"

[models.providers.default]
base_url = "http://llm.test/v1"
api_key = "secret"
models = ["gpt-test"]
`
	if err := os.WriteFile(configPath, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	restore := stubEnsureStateDeps(t)
	defer restore()
	EnsureIMBootstrapState = func(string) error { return nil }
	CreateManagerBot = func(_ context.Context, _, _ string, cfg config.Config) (bot.Bot, error) {
		if got, want := cfg.Server.ListenAddr, "127.0.0.1:19090"; got != want {
			t.Fatalf("cfg.Server.ListenAddr = %q, want %q", got, want)
		}
		return bot.Bot{}, nil
	}

	if _, err := EnsureState(context.Background(), EnsureStateOptions{ConfigPath: configPath}); err != nil {
		t.Fatalf("EnsureState() error = %v", err)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if string(data) != original {
		t.Fatalf("EnsureState() rewrote complete config.\nGot:\n%s\nWant:\n%s", string(data), original)
	}
}

func TestEnsureStateCompletesExistingConfigMissingBootstrapDefaults(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	configPath := filepath.Join(t.TempDir(), "config.toml")
	original := `[server]
listen_addr = "127.0.0.1:18080"
advertise_base_url = ""
access_token = "your_access_token"
`
	if err := os.WriteFile(configPath, []byte(original), 0o600); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	restore := stubEnsureStateDeps(t)
	defer restore()
	EnsureIMBootstrapState = func(string) error { return nil }
	CreateManagerBot = func(_ context.Context, _, _ string, cfg config.Config) (bot.Bot, error) {
		if got, want := cfg.Sandbox.Provider, config.DefaultSandboxProvider; got != want {
			t.Fatalf("cfg.Sandbox.Provider = %q, want %q", got, want)
		}
		return bot.Bot{}, nil
	}

	if _, err := EnsureState(context.Background(), EnsureStateOptions{ConfigPath: configPath}); err != nil {
		t.Fatalf("EnsureState() error = %v", err)
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	content := string(data)
	for _, want := range []string{
		`no_auth = false`,
		`[bootstrap]`,
		`manager_image_override = ""`,
		`[sandbox]`,
		`provider = "` + config.DefaultSandboxProvider + `"`,
		`home_dir_name = "` + config.DefaultSandboxHomeDirName + `"`,
		`debian_registries_override = []`,
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("completed config missing %q:\n%s", want, content)
		}
	}
}

func stubEnsureStateDeps(t *testing.T) func() {
	t.Helper()
	origCreateManager := CreateManagerBot
	origEnsureIMBootstrapState := EnsureIMBootstrapState
	return func() {
		CreateManagerBot = origCreateManager
		EnsureIMBootstrapState = origEnsureIMBootstrapState
	}
}
