name = "openclaw-manager"
description = "Builtin OpenClaw manager template"
role = "manager"
runtime_kind = "openclaw_sandbox"
updated_at = "2026-06-10T06:59:28Z"
version = "0.1.3"

[image]
ref = "opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsghq/openclaw-manager:0.1.3"
