name = "openclaw-manager"
description = "Builtin OpenClaw manager template"
role = "manager"
runtime_kind = "openclaw_sandbox"
updated_at = "2026-06-23T04:34:06Z"
version = "0.1.6"

[image]
ref = "opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsghq/openclaw:20260623.23-csgclaw"
