package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const FeishuChannelConfigFileName = "feishu.toml"

func DefaultFeishuChannelConfigPath() (string, error) {
	dir, err := DefaultDomainDir(ChannelsDirName)
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, FeishuChannelConfigFileName), nil
}

func FeishuChannelConfigPath(configPath string) (string, error) {
	configPath = strings.TrimSpace(configPath)
	if configPath == "" {
		return DefaultFeishuChannelConfigPath()
	}
	return filepath.Join(filepath.Dir(configPath), ChannelsDirName, FeishuChannelConfigFileName), nil
}

func LoadDefaultWithChannelFiles() (Config, error) {
	path, err := DefaultPath()
	if err != nil {
		return Config{}, err
	}
	return LoadWithChannelFiles(path)
}

func LoadWithChannelFiles(path string) (Config, error) {
	cfg, err := Load(path)
	if err != nil {
		return Config{}, err
	}

	feishuPath, err := FeishuChannelConfigPath(path)
	if err != nil {
		return Config{}, err
	}
	channels, ok, err := LoadFeishuChannelConfigIfExists(feishuPath)
	if err != nil {
		return Config{}, err
	}
	if ok {
		cfg.Channels.FeishuAdminOpenID = channels.FeishuAdminOpenID
		cfg.Channels.Feishu = channels.Feishu
	}
	return cfg, nil
}

func LoadFeishuChannelConfigIfExists(path string) (ChannelsConfig, bool, error) {
	channels, err := LoadFeishuChannelConfig(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return ChannelsConfig{}, false, nil
		}
		return ChannelsConfig{}, false, err
	}
	return channels, true, nil
}

func LoadFeishuChannelConfig(path string) (ChannelsConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return ChannelsConfig{}, err
		}
		return ChannelsConfig{}, fmt.Errorf("read feishu channel config: %w", err)
	}

	channels := ChannelsConfig{Feishu: make(map[string]FeishuConfig)}
	section := ""
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.TrimSpace(strings.Trim(line, "[]"))
			if section == "" {
				return ChannelsConfig{}, fmt.Errorf("invalid feishu channel config section")
			}
			continue
		}

		key, rawValue, ok := strings.Cut(line, "=")
		if !ok {
			return ChannelsConfig{}, fmt.Errorf("invalid feishu channel config line")
		}
		key = strings.TrimSpace(key)
		rawValue = strings.TrimSpace(rawValue)
		value, parseErr := parseFeishuChannelStringValue(rawValue)
		if parseErr != nil {
			return ChannelsConfig{}, fmt.Errorf("parse %s:%d %s: %w", path, lineNumber, key, parseErr)
		}

		switch {
		case section == "global":
			if key == "admin_open_id" {
				channels.FeishuAdminOpenID = value
			}
		case strings.HasPrefix(section, "bots."):
			botID := strings.TrimSpace(strings.TrimPrefix(section, "bots."))
			if err := ValidateFeishuChannelBotID(botID); err != nil {
				return ChannelsConfig{}, err
			}
			feishu := channels.Feishu[botID]
			switch key {
			case "app_id":
				feishu.AppID = value
			case "app_secret":
				feishu.AppSecret = value
			}
			channels.Feishu[botID] = feishu
		}
	}
	if err := scanner.Err(); err != nil {
		return ChannelsConfig{}, fmt.Errorf("scan feishu channel config: %w", err)
	}
	if len(channels.Feishu) == 0 {
		channels.Feishu = nil
	}
	return channels, nil
}

func parseFeishuChannelStringValue(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", nil
	}
	if strings.HasPrefix(raw, `"`) || strings.HasPrefix(raw, "'") {
		value, err := strconv.Unquote(raw)
		if err != nil {
			return "", err
		}
		return value, nil
	}
	return raw, nil
}

func SaveFeishuChannelConfig(path string, channels ChannelsConfig) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create feishu channel config dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("# Generated by csgclaw.\n")
	b.WriteString("# Feishu app secrets are intentionally stored outside config.toml.\n\n")
	if strings.TrimSpace(channels.FeishuAdminOpenID) != "" {
		fmt.Fprintf(&b, "[global]\nadmin_open_id = %q\n\n", channels.FeishuAdminOpenID)
	}

	names := make([]string, 0, len(channels.Feishu))
	for name := range channels.Feishu {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if err := ValidateFeishuChannelBotID(name); err != nil {
			return err
		}
		names = append(names, name)
	}
	sort.Strings(names)
	for i, name := range names {
		feishu := channels.Feishu[name]
		fmt.Fprintf(&b, "[bots.%s]\napp_id = %q\napp_secret = %q\n", name, feishu.AppID, feishu.AppSecret)
		if i != len(names)-1 {
			b.WriteString("\n")
		}
	}

	data := []byte(b.String())
	tmp, err := os.CreateTemp(filepath.Dir(path), ".feishu.toml.*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary feishu channel config: %w", err)
	}
	tmpPath := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(tmpPath)
		}
	}()
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod temporary feishu channel config: %w", err)
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temporary feishu channel config: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temporary feishu channel config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temporary feishu channel config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace feishu channel config: %w", err)
	}
	cleanup = false
	return nil
}

func ValidateFeishuChannelBotID(botID string) error {
	botID = strings.TrimSpace(botID)
	if botID == "" {
		return errors.New("bot_id is required")
	}
	for _, r := range botID {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '-' || r == '_':
		default:
			return fmt.Errorf("invalid bot_id %q: only letters, digits, '-' and '_' are allowed", botID)
		}
	}
	return nil
}
