package feishu

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"csgclaw/internal/config"
)

const FeishuChannelConfigFileName = "feishu.toml"

type Snapshot struct {
	AdminOpenID string
	Bots        map[string]AppConfig
}

type Store interface {
	Load() (Snapshot, error)
	LoadIfExists() (Snapshot, bool, error)
	Save(Snapshot) error
}

type FileStore struct {
	configPath string
}

func NewFileStore(configPath string) *FileStore {
	return &FileStore{configPath: strings.TrimSpace(configPath)}
}

func (s *FileStore) Load() (Snapshot, error) {
	path, err := s.path()
	if err != nil {
		return Snapshot{}, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Snapshot{}, err
		}
		return Snapshot{}, fmt.Errorf("read feishu channel config: %w", err)
	}

	snapshot := Snapshot{Bots: make(map[string]AppConfig)}
	section := ""
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.TrimSpace(strings.Trim(line, "[]"))
			if section == "" {
				return Snapshot{}, fmt.Errorf("invalid feishu channel config section")
			}
			continue
		}

		key, rawValue, ok := strings.Cut(line, "=")
		if !ok {
			return Snapshot{}, fmt.Errorf("invalid feishu channel config line")
		}
		key = strings.TrimSpace(key)
		rawValue = strings.TrimSpace(rawValue)
		value, parseErr := parseStoreStringValue(rawValue)
		if parseErr != nil {
			return Snapshot{}, fmt.Errorf("parse %s:%d %s: %w", path, lineNumber, key, parseErr)
		}

		switch {
		case section == "global":
			if key == "admin_open_id" {
				snapshot.AdminOpenID = value
			}
		case strings.HasPrefix(section, "bots."):
			botID := strings.TrimSpace(strings.TrimPrefix(section, "bots."))
			if err := ValidateBotID(botID); err != nil {
				return Snapshot{}, err
			}
			app := snapshot.Bots[botID]
			switch key {
			case "app_id":
				app.AppID = value
			case "app_secret":
				app.AppSecret = value
			}
			app.AdminOpenID = snapshot.AdminOpenID
			snapshot.Bots[botID] = app
		}
	}
	if err := scanner.Err(); err != nil {
		return Snapshot{}, fmt.Errorf("scan feishu channel config: %w", err)
	}
	if len(snapshot.Bots) == 0 {
		snapshot.Bots = nil
	}
	return normalizeSnapshot(snapshot), nil
}

func (s *FileStore) LoadIfExists() (Snapshot, bool, error) {
	snapshot, err := s.Load()
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Snapshot{}, false, nil
		}
		return Snapshot{}, false, err
	}
	return snapshot, true, nil
}

func (s *FileStore) Save(snapshot Snapshot) error {
	path, err := s.path()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create feishu channel config dir: %w", err)
	}

	snapshot = normalizeSnapshot(snapshot)

	var b strings.Builder
	b.WriteString("# Generated by csgclaw.\n")
	b.WriteString("# Feishu app secrets are intentionally stored outside config.toml.\n\n")
	if snapshot.AdminOpenID != "" {
		fmt.Fprintf(&b, "[global]\nadmin_open_id = %q\n\n", snapshot.AdminOpenID)
	}

	names := make([]string, 0, len(snapshot.Bots))
	for name := range snapshot.Bots {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if err := ValidateBotID(name); err != nil {
			return err
		}
		names = append(names, name)
	}
	sort.Strings(names)
	for i, name := range names {
		app := snapshot.Bots[name]
		fmt.Fprintf(&b, "[bots.%s]\napp_id = %q\napp_secret = %q\n", name, app.AppID, app.AppSecret)
		if i != len(names)-1 {
			b.WriteString("\n")
		}
	}

	data := []byte(b.String())
	tmp, err := os.CreateTemp(filepath.Dir(path), ".feishu.toml.*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary feishu channel config: %w", err)
	}
	tmpPath := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(tmpPath)
		}
	}()
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod temporary feishu channel config: %w", err)
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temporary feishu channel config: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temporary feishu channel config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temporary feishu channel config: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace feishu channel config: %w", err)
	}
	cleanup = false
	return nil
}

func (s *FileStore) path() (string, error) {
	return ChannelConfigPath(s.configPath)
}

func parseStoreStringValue(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", nil
	}
	if strings.HasPrefix(raw, `"`) || strings.HasPrefix(raw, "'") {
		value, err := strconv.Unquote(raw)
		if err != nil {
			return "", err
		}
		return value, nil
	}
	return raw, nil
}

func normalizeSnapshot(snapshot Snapshot) Snapshot {
	snapshot.AdminOpenID = strings.TrimSpace(snapshot.AdminOpenID)
	if len(snapshot.Bots) == 0 {
		snapshot.Bots = nil
		return snapshot
	}
	bots := make(map[string]AppConfig, len(snapshot.Bots))
	for botID, app := range snapshot.Bots {
		botID = strings.TrimSpace(botID)
		if botID == "" {
			continue
		}
		bots[botID] = AppConfig{
			AppID:       strings.TrimSpace(app.AppID),
			AppSecret:   strings.TrimSpace(app.AppSecret),
			AdminOpenID: snapshot.AdminOpenID,
		}
	}
	if len(bots) == 0 {
		snapshot.Bots = nil
		return snapshot
	}
	snapshot.Bots = bots
	return snapshot
}

func cloneSnapshot(snapshot Snapshot) Snapshot {
	snapshot = normalizeSnapshot(snapshot)
	if len(snapshot.Bots) == 0 {
		return Snapshot{AdminOpenID: snapshot.AdminOpenID}
	}
	cloned := Snapshot{
		AdminOpenID: snapshot.AdminOpenID,
		Bots:        make(map[string]AppConfig, len(snapshot.Bots)),
	}
	for botID, app := range snapshot.Bots {
		cloned.Bots[botID] = app
	}
	return cloned
}

func sortedSnapshotBotIDs(snapshot Snapshot) []string {
	ids := make([]string, 0, len(snapshot.Bots))
	for id := range snapshot.Bots {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

func DefaultChannelConfigPath() (string, error) {
	dir, err := config.DefaultDomainDir(config.ChannelsDirName)
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, FeishuChannelConfigFileName), nil
}

func ChannelConfigPath(configPath string) (string, error) {
	configPath = strings.TrimSpace(configPath)
	if configPath == "" {
		return DefaultChannelConfigPath()
	}
	return filepath.Join(filepath.Dir(configPath), config.ChannelsDirName, FeishuChannelConfigFileName), nil
}

func ValidateBotID(botID string) error {
	botID = strings.TrimSpace(botID)
	if botID == "" {
		return errors.New("bot_id is required")
	}
	for _, r := range botID {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '-' || r == '_':
		default:
			return fmt.Errorf("invalid bot_id %q: only letters, digits, '-' and '_' are allowed", botID)
		}
	}
	return nil
}
